### ISSUE TITLE
HOWTO: Apply different mappings per line

### ISSUE THREAD

**Issue by brettveenstra** [jehugaleahsa/FlatFiles#27]
Does this library support mappings to different POCOs per line?  Example being a "fixed file format" that intermingles different layouts within the same file.  The layouts could be driven by some criteria within each line or a "trigger"/marker in a PRIOR line.

**Comment by jehugaleahsa** [comment]
Sorry I didn't get back to your earlier. I got distracted right after archiving the email and then never came back around. You're actually the second person suggesting I support multiple mappings per file.

One option that still uses FlatFiles is to create a separate mapper/schema/reader for each POCO type. Then read the file yourself one row at a time and figure out which schema to use. Then wrap the current line with a `StringReader` and pass it to the reader, reading the first and only record.

I might add direct support for this in a future release, but I can guarantee this is how it will work in general (maybe with some insignificant performance improvements).

**Comment by stylefish** [comment]
for me this would also be a reeeaally helpful extension to the library. i have to read different records types in different lines like this:
```
This     Is     A              Header              Record    1 2 3344     555
This Is           LINE   Record 1
This Is           LINE   Record 2
This Is           LINE   Record 3
This        Is    A       Footer Record
```
so in this example i would use 3 different schemas.
i'm currently trying to implement this as you suggested and passing in a "StringReader" with the first line for the header, the last line for the footer and am currently thinking about how to solve the line types without reading everything into memory but removing the footer record from the stream given to the line schema reader.
i think i will implement a custom streamreader for this.

so: count me in for different record types in one file (and maybe a "is of type" method to check if the current line is of the given schema, maybe by checking record width and one or more fields in the record).

anyway, thank you very much for this library, i found nothing comparable to your schema. it's great for dynamic flat file solutions :) <3

**Comment by jehugaleahsa** [comment]
@stylefish I am looking into directly supporting this right now. It occurred to me that the length of the columns is a part of the schema. The only way I could let you choose a different schema per line is if I handed you a raw line (`This Is           LINE   Record 1`) and your code indicated which schema to use based on that and that alone. I couldn't let you inspect the split up record yet because I wouldn't have a schema.

Ultimately, there needs to be a `Func<string, Schema>` to grab the correct schema based on the record for fixed length files. For CSV files, it would be a `Func<string[], Schema>` since the number of columns is determined while parsing the record.

**Comment by jehugaleahsa** [comment]
@stylefish @brettveenstra With version 2.0, I have added direct support for multiple schemas in a file. Please read the README and/or the CHANGELOG for more details. For now, I have only provided support for *reading* but I plan on adding write support eventually. I increased the major version because there are some breaking changes with this release.
