### ISSUE TITLE
Multiple schema and mapper

### ISSUE THREAD

**Issue by mkokabi** [jehugaleahsa/FlatFiles#43]
Hi,
When I setup multiple schema with selector on FixedLength, there is only GetValues on reader which returns an array of objects. In your sample snippet in github 3 different mappers are also registered but I couldn't find how the mapper can be accessed in the events (according to your doc I assume this is the right way). Is there any sample about it. Basically, I have 3 classes for header, data and footer and I want to use the 3 mappers I created with the selector to get object values mapped to instance of each class.
Many thanks

**Comment by jehugaleahsa** [comment]
There's support for mapping two different ways, via raw object arrays or to
classes. It sounds like you're looking at the low-level object arrays
instead of the type mappers.
https://github.com/jehugaleahsa/FlatFiles/blob/master/README.md#files-containing-multiple-schemas

You want to use the FixedLengthTypeMapperSelector class. You pass it your
type mappers for header, data and footer records, along with a predicate.

**Comment by mkokabi** [comment]
Many thanks. I was creating SchemaSelector while I should be creating MapperSelector. It's working now.
