### ISSUE TITLE
Duvida

### ISSUE THREAD

**Issue by hbdbim** [jehugaleahsa/FlatFiles#46]
How to format a decimal (19.99) to (000000000001999)?
always with two decimal places.
for writing and reading, of course.

**Comment by jehugaleahsa** [comment]
I am pushing out a 4.4.0 release. I am going to eventually retire the `IColumnDefinition.Preprocessor` property. I have created 4 new lambda properties called `OnParsing`, `OnParsed`, `OnFormatting` and `OnFormatted` that get called before and after parsing and formatting values.

I am also adding support for setting an `IFormatProvider` on the options object to override the culture settings globally rather than needing to do it on each column individually.

You'll have to let me know whether the new delegate properties give you the flexibility you need.
