### ISSUE TITLE
XML Reader

### ISSUE THREAD

**Issue by felipepodolan** [jehugaleahsa/FlatFiles#88]
Thank you for the library, it is really helpful. Do you intend on adding XML parsing/reading features?
Thank you!

**Comment by jehugaleahsa** [comment]
Short answer: no.

I work mostly in Java these days and realized there's a ton of value in supporting the sort of schema definition this library provides, without actually doing any of the hard work of doing the actual parsing itself.

In the future, I might make a lighter-weight library that just supports defining schemas and then allows people to provide implementations that use said schema to parse physical files, wrapping other popular libraries like CsvReader.

At work, I needed to support reading parent/child/grandchild/etc. data from an XML file. I have a similar reader/schema approach for that, and for each parent record you can get a list of child records, and so on. Again... not writing an XML reader/writer... just wrapping it in an interface that makes it possible to describe navigating the XML structure. I don't see myself adding something like that to this library, since it's a little abstract (maybe need some xpath magic or something???) and this library is specific to CSV and fixed-width files these days.

**Comment by felipepodolan** [comment]
If you ever implement that, I think it would be really helpful. Applying the concept of this library to read/parse other types of file formats makes sense to me, it's the concept of ETL.
Basically, a library capable of parsing/reading files given a schema makes it easier for one to store the schema definition elsewhere and read/parse files with a generic code that is capable of parsing any file.
If one has to read/parse a new file, one just adds the definition of the file schema and is capable of reading it.
XML would be a great addition.
